import comp from "/Users/dkhoperiya/my-docs/src/.vuepress/.temp/pages/components/daily_reporting/change_log.html.vue"
const data = JSON.parse("{\"path\":\"/components/daily_reporting/change_log.html\",\"title\":\"Changelog\",\"lang\":\"ru-RU\",\"frontmatter\":{\"author\":\"David Khoperiya\",\"title\":\"Changelog\",\"date\":\"2024-04-18T00:00:00.000Z\",\"editLink\":false,\"pageview\":false,\"copyright\":false,\"footer\":\"Ozon.FinTech © 2024-2024 All rights reserved.\",\"description\":\"Release 2.1.0 (2024-04-19) Новые возможности Добавлена возможность настройки длительности работы SQL-сенсора (#FDEI-11) Прочее Добавлено название отчета в комментарий к отчету п...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/components/daily_reporting/change_log.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"FDEI Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Changelog\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Release 2.1.0 (2024-04-19) Новые возможности Добавлена возможность настройки длительности работы SQL-сенсора (#FDEI-11) Прочее Добавлено название отчета в комментарий к отчету п...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"ru-RU\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"David Khoperiya\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-04-18T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Changelog\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-04-18T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"David Khoperiya\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Release 2.1.0 (2024-04-19)\",\"slug\":\"release-2-1-0-2024-04-19\",\"link\":\"#release-2-1-0-2024-04-19\",\"children\":[{\"level\":3,\"title\":\"Новые возможности\",\"slug\":\"новые-возможности\",\"link\":\"#новые-возможности\",\"children\":[]},{\"level\":3,\"title\":\"Прочее\",\"slug\":\"прочее\",\"link\":\"#прочее\",\"children\":[]}]},{\"level\":2,\"title\":\"HotFix 2.0.1 (2024-04-12)\",\"slug\":\"hotfix-2-0-1-2024-04-12\",\"link\":\"#hotfix-2-0-1-2024-04-12\",\"children\":[{\"level\":3,\"title\":\"Исправления\",\"slug\":\"исправления\",\"link\":\"#исправления\",\"children\":[]}]},{\"level\":2,\"title\":\"Release 2.0.0 (2024-04-06)\",\"slug\":\"release-2-0-0-2024-04-06\",\"link\":\"#release-2-0-0-2024-04-06\",\"children\":[{\"level\":3,\"title\":\"Значительные изменения\",\"slug\":\"значительные-изменения\",\"link\":\"#значительные-изменения\",\"children\":[]},{\"level\":3,\"title\":\"Новые возможности\",\"slug\":\"новые-возможности-1\",\"link\":\"#новые-возможности-1\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.41,\"words\":122},\"filePathRelative\":\"components/daily_reporting/change_log.md\",\"localizedDate\":\"18 апреля 2024 г.\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
