import comp from "/Users/dkhoperiya/my-docs/src/.vuepress/.temp/pages/components/daily_reporting/user_guide.html.vue"
const data = JSON.parse("{\"path\":\"/components/daily_reporting/user_guide.html\",\"title\":\"User Guide\",\"lang\":\"ru-RU\",\"frontmatter\":{\"author\":\"David Khoperiya\",\"title\":\"User Guide\",\"date\":\"2024-04-18T00:00:00.000Z\",\"editLink\":false,\"pageview\":false,\"copyright\":false,\"footer\":\"Ozon.FinTech © 2024-2024 All rights reserved.\",\"description\":\"В данном разделе рассматриваются дополнительные кейсы настройки отчетов компоненты Daily Reporting 2.0. Настройки отчета Расписания Совет Данная настройка является необязательно...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/components/daily_reporting/user_guide.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"FDEI Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"User Guide\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"В данном разделе рассматриваются дополнительные кейсы настройки отчетов компоненты Daily Reporting 2.0. Настройки отчета Расписания Совет Данная настройка является необязательно...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"ru-RU\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"David Khoperiya\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-04-18T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"User Guide\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-04-18T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"David Khoperiya\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Настройки отчета\",\"slug\":\"настроики-отчета\",\"link\":\"#настроики-отчета\",\"children\":[{\"level\":3,\"title\":\"Расписания\",\"slug\":\"расписания\",\"link\":\"#расписания\",\"children\":[]},{\"level\":3,\"title\":\"Подключение\",\"slug\":\"подключение\",\"link\":\"#подключение\",\"children\":[]},{\"level\":3,\"title\":\"Сенсор\",\"slug\":\"сенсор\",\"link\":\"#сенсор\",\"children\":[]}]},{\"level\":2,\"title\":\"Настройки метрики\",\"slug\":\"настроики-метрики\",\"link\":\"#настроики-метрики\",\"children\":[{\"level\":3,\"title\":\"Запрос\",\"slug\":\"запрос\",\"link\":\"#запрос\",\"children\":[]},{\"level\":3,\"title\":\"Внешний вид\",\"slug\":\"внешнии-вид\",\"link\":\"#внешнии-вид\",\"children\":[]},{\"level\":3,\"title\":\"Сравнительные срезы\",\"slug\":\"сравнительные-срезы\",\"link\":\"#сравнительные-срезы\",\"children\":[]},{\"level\":3,\"title\":\"Кумулятивные срезы\",\"slug\":\"кумулятивные-срезы\",\"link\":\"#кумулятивные-срезы\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.3,\"words\":691},\"filePathRelative\":\"components/daily_reporting/user_guide.md\",\"localizedDate\":\"18 апреля 2024 г.\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
