export const themeData = JSON.parse("{\"encrypt\":{},\"darkmode\":\"disable\",\"logo\":\"/assets/icon/logo-128.svg\",\"docsDir\":\"src\",\"footer\":\"FDEI docs\",\"displayFooter\":true,\"locales\":{\"/\":{\"lang\":\"ru-RU\",\"navbarLocales\":{\"langName\":\"Русский\",\"selectLangAriaLabel\":\"Выберите язык\"},\"metaLocales\":{\"author\":\"Автор\",\"date\":\"Дата написания\",\"origin\":\"Оригинал\",\"views\":\"Просмотры страницы\",\"category\":\"Категория\",\"tag\":\"Тэги\",\"readingTime\":\"Время чтения\",\"words\":\"Слова\",\"toc\":\"На этой странице\",\"prev\":\"Предыдущая\",\"next\":\"Следующая\",\"lastUpdated\":\"Последнее обновление\",\"contributors\":\"Контрибьюторы\",\"editLink\":\"Редактировать эту страницу\",\"print\":\"Печать\"},\"outlookLocales\":{\"themeColor\":\"Цвет темы\",\"darkmode\":\"Режим темы\",\"fullscreen\":\"Полный экран\"},\"routeLocales\":{\"skipToContent\":\"Перейти к основному содержанию\",\"notFoundTitle\":\"Страница не найдена\",\"notFoundMsg\":[\"Здесь ничего нет.\",\"Как мы сюда попали?\",\"Это четыре-о-четыре.\",\"Похоже, у нас есть несколько неработающих ссылок.\"],\"back\":\"Вернуться назад\",\"home\":\"Вернуться на главную\",\"openInNewWindow\":\"Открыть в новом окне\"},\"navbar\":[{\"text\":\"Главная\",\"icon\":\"home\",\"link\":\"/\"},{\"text\":\"Компоненты\",\"icon\":\"box\",\"link\":\"/components/\"},{\"text\":\"Операторы\",\"icon\":\"gear\",\"link\":\"/operators/\"},{\"text\":\"Python API\",\"icon\":\"fa-brands fa-python\",\"link\":\"/python_api/\"},{\"text\":\"Демо\",\"icon\":\"chalkboard-user\",\"link\":\"/demo/\"}],\"sidebar\":{\"/components/\":[{\"text\":\"Компоненты\",\"link\":\"/components/\",\"icon\":\"box\",\"collapsible\":false,\"children\":[{\"text\":\"Daily Reporting 2.0\",\"icon\":\"image\",\"prefix\":\"daily_reporting/\",\"collapsible\":true,\"children\":[\"overview/\",\"quick_start/\",\"user_guide/\",\"changelog/\"]},{\"text\":\"CDM/DDS\",\"icon\":\"table\",\"prefix\":\"cdm_dds/\",\"collapsible\":true,\"children\":[\"overview\",\"quick_start\",\"user_guide\",\"change_log\"]},{\"text\":\"Progress Goal\",\"icon\":\"clipboard-check\",\"prefix\":\"progress_goal/\",\"collapsible\":true,\"children\":[\"overview\",\"quick_start\",\"user_guide\",\"change_log\"]},{\"text\":\"Event Log\",\"icon\":\"gears\",\"prefix\":\"event_log/\",\"collapsible\":true,\"children\":[\"overview\",\"quick_start\",\"user_guide\",\"change_log\"]}]}],\"/demo/\":[{\"text\":\"Компоненты\",\"link\":\"\",\"collapsible\":false,\"children\":[\"Demo_2024-04-17\"]}]}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
